server:
  port: 9191

#MySQL Database Configuration:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Sourav#8699
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: PRODUCT-SERVICE

  config:
    import: optional:configserver:http://localhost:8088

#Fault Tolerance Retry Configuration:
resilience4j:
  retry:
    instances:
      productService:
        maxAttempts: 2
        waitDuration: 3s

#Actuator Endpoint Configuration:
management:
  #Prometheus Configuration:
  observations:
    key-values:
      application: PRODUCT-SERVICE

#Logging Visibility Configuration:
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
