server:
  port: 9191

#MySQL Database Configuration:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Sourav#8699
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: PRODUCT-SERVICE

#Eureka Server Configuration:
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # Indicates whether this instance should register its information with eureka server for discovery by others
    fetch-registry: true # Indicates whether this client should fetch eureka registry information from eureka server.
    service-url:
      defaultZone: http://localhost:8761/eureka
    should-unregister-on-shutdown: true

resilience4j:
  retry:
    instances:
      productService:
        maxAttempts: 2
        waitDuration: 3s

#Actuator Endpoint Configuration:
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

  #Prometheus Configuration:
  observations:
    key-values:
      application: PRODUCT-SERVICE
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

  #Tracing Configuration:
  tracing:
    sampling:
      probability: 1.0 # sampling all in dev, reduce it in prod to save loading

#Logging Visibility Configuration:
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

# While multiple instances are running if we change any configuration
# we need to refresh all the running instance og the application
# using @RefreshScope annotation and need to hit /actuator/refresh
# and we need to hit /actuator/refresh end point for all the running instance
# so to solve this problem we have spring-cloud-bus using this we can
# refresh any instance by hitting /actuator/bus-refresh and all the instance
# will get the updated configuration.
com:
  ms:
    spring-cloud:
      prop: local-bus