global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'COUPON-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'PRODUCT-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9191'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'API-GATEWAY'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9095'] ## only for demo purposes don't use host.docker.internal in production